name: Build Gradle project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
          
      - name: Run build
        run: ./gradlew clean build
        env:
          GITHUB_USER: "github"
          GITHUB_TOKEN: ${{ github.token }}
      